"""Per-file complexity ratchet: counts of C901/PLR0913/PLR0915 findings may fall, never rise.

Why this exists on top of ruff's own baseline: a ``per-file-ignores`` entry
silences a rule for the WHOLE file, so once a file is baselined a brand-new
complexity-15 function in it passes untouched. This script runs ruff with
``--isolated`` (so per-file-ignores do not apply), counts findings per
``(file, rule)``, and compares against ``complexity-baseline.json``.

A count ABOVE its baseline fails (growth). A count BELOW its baseline also
fails: silent headroom to regress into with CI green. Lock the improvement in
with ``--update`` in the same change that earned it.

Usage::

    python scripts/check_complexity_ratchet.py            # enforce
    python scripts/check_complexity_ratchet.py --update   # rewrite the baseline
"""

from __future__ import annotations

import json
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _check_runner import report  # noqa: E402

REPO = Path(__file__).resolve().parents[1]
BASELINE = REPO / "complexity-baseline.json"
RULES = ("C901", "PLR0913", "PLR0915")
SCAN_DIRS = ("app", "scripts")
COMMENT = (
    "Complexity ratchet baseline: counts of C901/PLR0913/PLR0915 findings per file, generated by "
    "scripts/check_complexity_ratchet.py --update. Counts may only fall: CI fails if any count rises "
    "or a new file appears, and a stale (too-high) entry also fails so improvements get locked in."
)


def measure() -> dict[str, dict[str, int]]:
    """Current findings per (file, rule) with ruff --isolated."""
    cmd = [
        "ruff",
        "check",
        "--isolated",
        "--select",
        ",".join(RULES),
        "--output-format",
        "json",
        "--config",
        "lint.mccabe.max-complexity=10",
        "--config",
        "lint.pylint.max-args=5",
        "--config",
        "lint.pylint.max-statements=50",
        "--exit-zero",
        *SCAN_DIRS,
    ]
    out = subprocess.run(cmd, capture_output=True, text=True, cwd=REPO, check=False)
    if out.returncode not in (0, 1):
        raise RuntimeError(f"ruff failed: {out.stderr.strip()}")
    counts: dict[str, dict[str, int]] = defaultdict(lambda: defaultdict(int))
    for finding in json.loads(out.stdout or "[]"):
        rel = Path(finding["filename"]).resolve().relative_to(REPO).as_posix()
        counts[rel][finding["code"]] += 1
    return {f: dict(sorted(r.items())) for f, r in sorted(counts.items())}


def load_baseline() -> dict[str, dict[str, int]]:
    """Baseline counts from disk (empty if absent)."""
    if not BASELINE.exists():
        return {}
    data = json.loads(BASELINE.read_text(encoding="utf-8"))
    return {k: dict(v) for k, v in data.get("counts", {}).items()}


def compare(current: dict[str, dict[str, int]], baseline: dict[str, dict[str, int]]) -> list[str]:
    """Violations: any rise, any new file, and any stale (too-high) baseline entry."""
    out: list[str] = []
    for file, rules in current.items():
        for rule, n in rules.items():
            allowed = baseline.get(file, {}).get(rule, 0)
            if n > allowed:
                out.append(
                    f"{file}: {rule} rose {allowed} -> {n}; simplify, or argue the increase and run --update"
                )
    for file, rules in baseline.items():
        for rule, allowed in rules.items():
            n = current.get(file, {}).get(rule, 0)
            if n < allowed:
                out.append(
                    f"{file}: {rule} improved {allowed} -> {n}; lock it in with `make lint.complexity.update`"
                )
    return sorted(out)


def write_baseline(counts: dict[str, dict[str, int]]) -> None:
    """Persist ``counts`` as the new baseline."""
    BASELINE.write_text(
        json.dumps({"_comment": COMMENT, "counts": counts}, indent=2) + "\n", encoding="utf-8"
    )


def main(argv: list[str] | None = None) -> int:
    args = argv if argv is not None else sys.argv[1:]
    current = measure()
    if "--update" in args:
        write_baseline(current)
        print(
            f"complexity baseline written: {sum(sum(r.values()) for r in current.values())} findings"
        )
        return 0
    return report(
        "Complexity ratchet", compare(current, load_baseline()), ok_message="complexity ratchet: OK"
    )


if __name__ == "__main__":
    raise SystemExit(main())
