"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

Conventions (CLAUDE.md "Migration Workflow"):
* New tables: create exactly as defined; downgrade with explicit op.drop_table(),
  never SQLModel.metadata.drop_all(). Drop enum types this revision created, after
  the tables that used them.
* Existing tables: keep the minimal autogenerated op.* statements. Never
  drop/recreate a production table to change columns.
* Index builds: postgresql_concurrently=True inside op.get_context().autocommit_block()
  (scripts/check_migration_safety.py enforces this on new revisions).
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
${imports if imports else ""}

revision: str = ${repr(up_revision)}
down_revision: str | None = ${repr(down_revision)}
branch_labels: str | Sequence[str] | None = ${repr(branch_labels)}
depends_on: str | Sequence[str] | None = ${repr(depends_on)}


def upgrade() -> None:
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    ${downgrades if downgrades else "pass"}
